# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' K-means Algorithm Using C++
#' 
#' This function implements the K-means algorithm using C++.
#' 
#' The K-means algorithm was first proposed by James MacQueen (1967)
#' <Doi:10.1.1.308.8619>. Users can either specify the initial cluster centers
#' directly or just the number of cluster centers.
#' 
#' @param data a matrix, each row represents a sample.
#' @param centers a matrix, each row represents a cluster center. Default is NA.
#' @param k numeric, number of cluster centers. Default is NA.
#' 
#' @export
myKmeans_C <- function(data, centers = matrix(2,2), k = 0L) {
    .Call('_myKmeans3_myKmeans_C', PACKAGE = 'myKmeans3', data, centers, k)
}

